/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

typedef volatile unsigned int vuint32_t;

#define RCC_BASE       0x40021000
#define RCC_CFGR       (*(vuint32_t *)(RCC_BASE + 0x04))
#define RCC_CR         (*(vuint32_t *)(RCC_BASE + 0x00))
#define RCC_APB2ENR    (*(vuint32_t *)(RCC_BASE + 0x18))

#define GPIOA_BASE     0x40010800
#define GPIOA_CRL      (*(vuint32_t *)(GPIOA_BASE + 0x00))
#define GPIOA_CRH      (*(vuint32_t *)(GPIOA_BASE + 0x04))
#define GPIOA_ODR      (*(vuint32_t *)(GPIOA_BASE + 0x0C))
#define AFIO_EXTICR1   (*(vuint32_t *)(0x40010008))

#define NVIC_ISER0     (*(vuint32_t *)(0xE000E100))
#define EXTI_BASE      0x40010400
#define EXTI_IMR       (*(vuint32_t *)(EXTI_BASE + 0x00))
#define EXTI_RTSR      (*(vuint32_t *)(EXTI_BASE + 0x08))
#define EXTI_FTSR      (*(vuint32_t *)(EXTI_BASE + 0x0C))
#define EXTI_PR        (*(vuint32_t *)(EXTI_BASE + 0x14))

void Clock_init(void){

	/* Enable IO port  CLOCK */
	RCC_APB2ENR |= 1 << 2;
	/* Enable AFIO clock */
	RCC_APB2ENR |= 1 << 0;

}

int main(void)
{
	Clock_init();

	/* InitGPIOA Pin13 Output */
	GPIOA_CRH &= 0xFF0FFFFF;
	GPIOA_CRH |= 0x00200000;
	/* Pin as Floating input */
	GPIOA_CRL |= (0b01) << 2;

	/* Select PINA0 as EXTI0 */
	AFIO_EXTICR1 |= (0b0000) << 0;

	/* Rising trigger enable */
	EXTI_RTSR |= 1 << 0;

	/* Enable Mask EXTI0 */
	EXTI_IMR |= 1 << 0;

	/* Enable NVIC IRQ 6 (EXTI0) */
	NVIC_ISER0 |= 1 << 6;

	while(1);
}

void EXTI0_IRQHandler(void){

	/* Toggle Led */
	GPIOA_ODR ^= 1 << 13;
	/* Clear Pending flag */
	EXTI_PR |= 1 << 0;
}
